version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - sql_network
    volumes:
      - /mysql_data :/var/lib/mysql

  python_app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - sql_network
    depends_on:
      - mysql

networks:
  sql_network:

# version: '3'

# services:
#   mysql:
#     image: mysql:latest
#     expose:
#       - 3306
#     # ports:
#     #   - 3307:3306
#     networks:
#       - hdb_alert_network
#     environment:
#       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_SECRET
#       MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE_SECRET
#       MYSQL_USER_FILE: /run/secrets/MYSQL_USER_SECRET
#       MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_SECRET
#       MYSQL_HOST: mysql
#     volumes:
#       - /srv/dev-disk-by-uuid-a6c6051a-8b8a-42a5-9851-8cee39a32197/data/hdbalert/mysql_data_new:/var/lib/mysql
#     secrets:
#       - MYSQL_ROOT_PASSWORD_SECRET
#       - MYSQL_DATABASE_SECRET
#       - MYSQL_PASSWORD_SECRET
#       - MYSQL_USER_SECRET

#   python_app:
#     image: hashketh/hdb-alert:linuxarm64-phase1
#     networks:
#       - hdb_alert_network
#     ports:
#       - "5000:5000"
#     environment:
#       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD_SECRET
#       MYSQL_DATABASE_FILE: /run/secrets/MYSQL_DATABASE_SECRET
#       MYSQL_USER_FILE: /run/secrets/MYSQL_USER_SECRET
#       MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD_SECRET
#       MYSQL_HOST: mysql
#       MYSQL_PORT: 3306
#     depends_on:
#       - mysql
#     volumes:
#       - /srv/dev-disk-by-uuid-a6c6051a-8b8a-42a5-9851-8cee39a32197/data/hdbalert/app:/app  # Mount your Python application code
#     secrets:
#       - MYSQL_ROOT_PASSWORD_SECRET
#       - MYSQL_DATABASE_SECRET
#       - MYSQL_PASSWORD_SECRET
#       - MYSQL_USER_SECRET

# volumes:
#   mysql_data:
# networks:
#   hdb_alert_network:
# secrets:
#   MYSQL_ROOT_PASSWORD_SECRET:
#     external: true
#   MYSQL_DATABASE_SECRET:
#     external: true
#   MYSQL_PASSWORD_SECRET:
#     external: true
#   MYSQL_USER_SECRET:
#     external: true