version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - sql_network
    volumes:
      - /mysql_data :/var/lib/mysql

  python_app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - sql_network
    depends_on:
      - mysql

networks:
  sql_network:

# version: '3'

# services:
#   mysql:
#     image: mysql:latest
#     ports:
#       - "3307:3306"
#     networks:
#       - sql_network
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: db
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     volumes:
#       - /srv/dev-disk-by-uuid-a6c6051a-8b8a-42a5-9851-8cee39a32197/data/hdbalert/mysql_data:/var/lib/mysql

#   python_app:
#     image: hashketh/hdb-alert:0.1linux64
#     networks:
#       - sql_network
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mysql
#     volumes:
#       - /srv/dev-disk-by-uuid-a6c6051a-8b8a-42a5-9851-8cee39a32197/data/hdbalert/app:/app  # Mount your Python application code

# volumes:
#   mysql_data:
# networks:
#   sql_network: