version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  hdb-app:
    image: hashketh/hdb-resale-alert:0.4
    container_name: hdb-app-container
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./path/to/your/flask/app:/app