version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    networks:
      - sql_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: db
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql

  python_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - sql_network
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./app:/app  # Mount your Python application code

volumes:
  mysql_data:
networks:
  sql_network: