version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - sql_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql
    extra_hosts:
      - "mysql:172.20.0.2"

  python_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - sql_network
    depends_on:
      - mysql
    volumes:
      - ./app:/app  # Mount your Python application code

volumes:
  mysql_data:
networks:
  sql_network: